### ISSUE TITLE
Can I specify a path for my `flambe-output` dir?

### ISSUE THREAD

**Issue by williamabrwolf** [Open-ASAPP/flambe#11]

**Comment by jeremyasapp** [comment]
Yes, the argument is called `save_path` at the `Experiment` level.
See: http://flambe.ai/en/latest/autoapi/flambe/experiment/experiment/index.html

**Comment by nmatthews-asapp** [comment]
@williamabrwolf does this fully answer your question?

**Comment by williamabrwolf** [comment]
yep!
