### ISSUE TITLE
Clearer error message when an extension is not installed.

### ISSUE THREAD

**Issue by yukw777** [Open-ASAPP/flambe#14]
**Describe the bug**
When you run a runnable one of whose components uses an extension that hasn't been installed (`pip install` or `flambe -i`), flambe throws the following error, which does not tell the user what is actually going on:
```
11:35:30 | AttributeError("'CommentedMap' object has no attribute 'add_extensions_metadata'",)
Traceback (most recent call last):
  File "/home/peter/code/sci-summary/venv/lib/python3.6/site-packages/flambe/runner/run.py", line 87, in main
    runnable.run(force=args.force, verbose=args.verbose)
  File "/home/peter/code/sci-summary/venv/lib/python3.6/site-packages/flambe/experiment/experiment.py", line 279, in run
    schema_block.add_extensions_metadata(self.extensions)
AttributeError: 'CommentedMap' object has no attribute 'add_extensions_metadata'
```

**To Reproduce**
1. Create a yaml file with an extension.
1. Run it (do not install the extension)

**Expected behavior**
A better error message that tells the user to install the extension.

**Screenshots**

**Software Versions (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python Version 3.6.8
 - PyTorch Version 1.1.0
 - Flambé Version 0.4.1

**Additional context**

**Comment by jeremyasapp** [comment]
@nmatthews-asapp can we detect this somehow?

**Comment by jeremyasapp** [comment]
@yukw777 I'm not able to replicate this error. When I have an uninstalled extension, I receive the following error message:
```
ImportError: Error importing dummy_extensions: No module named 'dummy_extensions'. Please 'pip install' the package manually or use '-i' flag (only applies when running flambe as cmd line program)
```
