### ISSUE TITLE
can flambe save all tensorboard plots to a specified dir?

### ISSUE THREAD

**Issue by williamabrwolf** [Open-ASAPP/flambe#34]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

I'd like a `tb_plots_save_dir` option in the Flambe config; if given, the runner saves all TensorBoard plots to that dir.

**Describe alternatives you've considered**

Writing a tool to do this myself.

**Additional context**

Erm, no.

**Comment by jeremyasapp** [comment]
Is the current output directory not sufficient? Can you provide a use case for this feature?

**Comment by williamabrwolf** [comment]
You want to delete the output after the run terminates, but keep the plots!

**Comment by williamabrwolf** [comment]
Where can these plots be found in the output directory, currently?

**Comment by jeremyasapp** [comment]
Ah i see. I don't think this is supported in Tensorboard: https://github.com/tensorflow/tensorboard/issues/32.

We plan on having a report mechanism is Flambé to create plots and whatnot that will not depend on tensorboard. It's in the agenda for Flambe 0.5, and will likely cover your use case.

**Comment by jeremyasapp** [comment]
Closing for now :)
